server:
  port: 8080
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/shiro?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        view:
          prefix: /WEB-INF/views
          suffix: .html
    redis:
          database: 1
          host: 192.168.1.100
          port: 6379
          password:       # 密码（默认为空）
          timeout: 6000  # 连接超时时长（毫秒）
          jedis:
            pool:
              max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
              max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-idle: 10      # 连接池中的最大空闲连接
              min-idle: 5       # 连接池中的最小空闲连接
mybatis-plus:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.lijincan.pojo

